version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: player
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  video-storage:
#    image: nginx:latest
#    volumes:
#      - ./videos:/usr/share/nginx/html/videos
#    ports:
#      - "8081:80"
#    restart: always

volumes:
  postgres_data:
