create table if not exists categories
(
    id              bigint generated by default as identity
                    primary key,
    name            varchar(255) not null unique
);

create table if not exists users
(
    id              bigint generated by default as identity
                    primary key,
    password        varchar(255) not null,
    role            varchar(255) not null,
    username        varchar(255) not null unique
);

create table if not exists videos
(
    id              bigint generated by default as identity
                    primary key,
    description     varchar(255) not null,
    file_id         varchar(255) not null,
    thumbnail_url   varchar(255),
    title           varchar(255) not null,
    category_id     integer      not null references categories
);

create table if not exists heroes
(
    id              bigint generated by default as identity
                    primary key,
    name            varchar(50) not null
                    unique,
    category_id     integer references categories,
    description     text
);

