CREATE TABLE if not exists users
(
    id       BIGSERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255)        NOT NULL,
    role     VARCHAR(255)        NOT NULL
);
create table if not exists categories
(
    id            bigint default nextval('categories_id_seq'::regclass) not null
        primary key,
    title         varchar(50)                                           not null
        unique,
    thumbnail_url varchar(255)                                          not null,
    name          varchar(255)                                          not null
        constraint ukt8o6pivur7nn124jehx7cygw5
            unique
);

create table if not exists heroes
(
    id          serial
        primary key,
    name        varchar(50) not null
        unique,
    category_id integer
        references categories,
    description text
);

create table if not exists replays
(
    id            serial
        primary key,
    hero_id       integer
        references heroes,
    file_path     varchar(255) not null,
    thumbnail_url varchar(255) not null,
    upload_date   date
);

create table if not exists videos
(
    id            integer generated by default as identity
        primary key,
    description   varchar(255) not null,
    file_id       varchar(255) not null,
    thumbnail_url varchar(255),
    title         varchar(255) not null,
    category_id   bigint       not null
        constraint fk757y9y2j67t6nl4h5746si1rx
            references categories
);